spring.application.name=construction_management

spring.datasource.url=jdbc:mysql://localhost:3306/construction_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pasindu123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080
app.auth.admin.username=admin
app.auth.admin.password=Admin@123

app.auth.client-manager.username=clientmanager
app.auth.client-manager.password=ClientManager@123

app.auth.project-manager.username=projectmanager
app.auth.project-manager.password=ProjectManager@123

app.auth.employee-manager.username=employeemanager
app.auth.employee-manager.password=EmployeeManager@123

app.auth.inventory-manager.username=inventorymanager
app.auth.inventory-manager.password=InventoryManager@123




